#!/usr/bin/env python3
"""Land this repository's commit on a ScienceAccelBench checkout (the mechanical sync).

    python3 tools/release.py --dest <ScienceAccelBench checkout> [--pr] [--allow-unpushed]

What it does, in order:
  1. Reads this checkout's HEAD commit. Refuses a dirty tree, and refuses a
     commit that is not on origin/main unless --allow-unpushed is given, so the
     revision written into vendor-manifest.json is always a merged commit.
  2. Runs tools/export_scienceaccelbench.py into <dest> with that commit as
     --revision, then runs the benchmark's scripts/vendor_sync.py verify.
  3. Reports what changed under skills/package-sciaccel-task/. If nothing did,
     the benchmark is already in sync and the script stops.
  4. Without --pr: prints the commit / push / PR commands and stops.
     With --pr: creates sync/pipeline-<sha7> from the benchmark's current
     branch (which must be main), commits the generated files, pushes, and
     opens the benchmark PR with `gh`.

Nothing is deleted on either side. Stale generated files on the benchmark are
reported by verify and left for a human to remove.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
EXPORTER = REPO / "tools" / "export_scienceaccelbench.py"
SKILL_REL = Path("skills") / "package-sciaccel-task"


def git(cwd: Path, *args: str, check: bool = True) -> str:
    proc = subprocess.run(["git", *args], cwd=str(cwd), capture_output=True, text=True)
    if check and proc.returncode != 0:
        raise SystemExit(f"release: git {' '.join(args)} failed in {cwd}:\n{proc.stderr.strip()}")
    return proc.stdout.strip()


def canonical_commit(allow_unpushed: bool) -> tuple[str, str]:
    if git(REPO, "status", "--porcelain"):
        raise SystemExit("release: this checkout has uncommitted changes; commit or stash them first")
    sha = git(REPO, "rev-parse", "HEAD")
    subject = git(REPO, "log", "-1", "--format=%s", sha)
    fetched = subprocess.run(["git", "fetch", "-q", "origin", "main"], cwd=str(REPO),
                             capture_output=True, text=True).returncode == 0
    on_main = fetched and subprocess.run(["git", "merge-base", "--is-ancestor", sha, "origin/main"],
                                         cwd=str(REPO)).returncode == 0
    if not on_main:
        why = "origin/main could not be fetched" if not fetched else "HEAD is not on origin/main"
        if not allow_unpushed:
            raise SystemExit(f"release: {why}; merge first, or pass --allow-unpushed to record an unmerged commit")
        print(f"release: WARNING: {why}; recording {sha[:12]} anyway (--allow-unpushed)")
    return sha, subject


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--dest", required=True, help="ScienceAccelBench checkout root")
    parser.add_argument("--pr", action="store_true", help="commit on sync/pipeline-<sha7>, push, and open the benchmark PR")
    parser.add_argument("--allow-unpushed", action="store_true", help="record a commit that is not on origin/main")
    args = parser.parse_args(argv)

    dest = Path(args.dest).expanduser().resolve()
    if not (dest / "skills").is_dir() or not (dest / ".git").exists():
        raise SystemExit(f"release: --dest must be a ScienceAccelBench git checkout (has skills/ and .git): {dest}")
    if git(dest, "status", "--porcelain", "--", str(SKILL_REL)):
        raise SystemExit(f"release: {dest / SKILL_REL} has uncommitted changes; start from a clean checkout")

    sha, subject = canonical_commit(args.allow_unpushed)
    print(f"release: canonical {sha[:12]} \"{subject}\"")
    rc = subprocess.run([sys.executable, str(EXPORTER), "--dest", str(dest), "--revision", sha]).returncode
    if rc != 0:
        return rc
    rc = subprocess.run([sys.executable, str(dest / SKILL_REL / "scripts" / "vendor_sync.py"), "verify"],
                        cwd=str(dest)).returncode
    if rc != 0:
        return rc

    changed = git(dest, "status", "--porcelain", "--", str(SKILL_REL))
    if not changed:
        print(f"release: {dest} is already in sync with {sha[:12]}; nothing to land")
        return 0
    print("release: generated changes on the benchmark side:")
    for line in changed.splitlines():
        print(f"  {line}")

    branch = f"sync/pipeline-{sha[:7]}"
    title = f"sync: pipeline {sha[:7]} — {subject}"
    body = (f"Mechanical export of aitofound/sciaccelbench-pipeline @ `{sha}`\n\n"
            f"> {subject}\n\n"
            "Generated by `tools/release.py`; the diff is exactly the exporter's output plus "
            "`vendor-manifest.json`. `scripts/vendor_sync.py verify` passes offline.\n")
    if not args.pr:
        print("\nrelease: to land it:")
        print(f"  git -C {dest} checkout -b {branch}")
        print(f"  git -C {dest} add {SKILL_REL}")
        print(f"  git -C {dest} commit -m {title!r}")
        print(f"  git -C {dest} push -u origin {branch}")
        print(f"  gh pr create --repo <benchmark> --head {branch} --title {title!r} --body '<see release.py>'")
        return 0

    current = git(dest, "rev-parse", "--abbrev-ref", "HEAD")
    if current != "main":
        raise SystemExit(f"release: the benchmark checkout is on {current!r}; --pr branches from main only")
    git(dest, "checkout", "-q", "-b", branch)
    git(dest, "add", "--", str(SKILL_REL))
    git(dest, "commit", "-q", "-m", title)
    git(dest, "push", "-q", "-u", "origin", branch)
    proc = subprocess.run(["gh", "pr", "create", "--head", branch, "--title", title, "--body", body],
                          cwd=str(dest), capture_output=True, text=True)
    if proc.returncode != 0:
        print(proc.stderr.strip())
        raise SystemExit("release: branch pushed but `gh pr create` failed; open the PR by hand")
    print(f"release: opened {proc.stdout.strip()}")
    print("release: wait for the benchmark CI, then merge that PR. The benchmark checkout is left on the sync branch.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
