#!/usr/bin/env python3
"""Pin this repository's commit on a ScienceAccelBench checkout (the mechanical sync).

    python3 tools/release.py --dest <ScienceAccelBench checkout> [--pr] [--allow-unpushed]

The benchmark carries no copy of the pipeline. Its
skills/package-sciaccel-task/PIPELINE_REVISION names the commit of this
repository that its CI and its authors run, and this script bumps that pin:

  1. Reads this checkout's HEAD commit. Refuses a dirty tree, and refuses a
     commit that is not on origin/main unless --allow-unpushed is given, so the
     pin is always a merged commit.
  2. Writes the full sha into <dest>/skills/package-sciaccel-task/PIPELINE_REVISION.
     If the file already holds it, the benchmark is in sync and the script stops.
  3. Without --pr: prints the commit / push / PR commands and stops.
     With --pr: creates sync/pipeline-<sha7> from the benchmark's current
     branch (which must be main), commits the pin, pushes, and opens the
     benchmark PR with `gh`.

Nothing else on the benchmark side is touched; the pointer SKILL.md and the
loader scripts/sab.py there are hand-maintained and change only when the
pipeline's location or its loading rule changes.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SKILL_REL = Path("skills") / "package-sciaccel-task"
PIN_REL = SKILL_REL / "PIPELINE_REVISION"
UPSTREAM_REPO = "https://github.com/huangzesen/sciaccelbench-pipeline"


def git(cwd: Path, *args: str, check: bool = True) -> str:
    proc = subprocess.run(["git", *args], cwd=str(cwd), capture_output=True, text=True)
    if check and proc.returncode != 0:
        raise SystemExit(f"release: git {' '.join(args)} failed in {cwd}:\n{proc.stderr.strip()}")
    return proc.stdout.strip()


def skill_revision() -> str:
    m = re.search(r'^REVISION\s*=\s*"([^"]+)"', (REPO / "src" / "sciaccel_pipeline" / "config.py").read_text(), re.M)
    return m.group(1) if m else "unknown"


def canonical_commit(allow_unpushed: bool) -> tuple[str, str]:
    if git(REPO, "status", "--porcelain"):
        raise SystemExit("release: this checkout has uncommitted changes; commit or stash them first")
    sha = git(REPO, "rev-parse", "HEAD")
    subject = git(REPO, "log", "-1", "--format=%s", sha)
    fetched = subprocess.run(["git", "fetch", "-q", "origin", "main"], cwd=str(REPO),
                             capture_output=True, text=True).returncode == 0
    on_main = fetched and subprocess.run(["git", "merge-base", "--is-ancestor", sha, "origin/main"],
                                         cwd=str(REPO)).returncode == 0
    if not on_main:
        why = "origin/main could not be fetched" if not fetched else "HEAD is not on origin/main"
        if not allow_unpushed:
            raise SystemExit(f"release: {why}; merge first, or pass --allow-unpushed to pin an unmerged commit")
        print(f"release: WARNING: {why}; pinning {sha[:12]} anyway (--allow-unpushed)")
    return sha, subject


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--dest", required=True, help="ScienceAccelBench checkout root")
    parser.add_argument("--pr", action="store_true", help="commit on sync/pipeline-<sha7>, push, and open the benchmark PR")
    parser.add_argument("--allow-unpushed", action="store_true", help="pin a commit that is not on origin/main")
    args = parser.parse_args(argv)

    dest = Path(args.dest).expanduser().resolve()
    if not (dest / "skills").is_dir() or not (dest / ".git").exists():
        raise SystemExit(f"release: --dest must be a ScienceAccelBench git checkout (has skills/ and .git): {dest}")
    if git(dest, "status", "--porcelain", "--", str(SKILL_REL)):
        raise SystemExit(f"release: {dest / SKILL_REL} has uncommitted changes; start from a clean checkout")
    pin = dest / PIN_REL
    if not pin.is_file():
        raise SystemExit(f"release: {pin} is missing; this benchmark checkout predates the pin model (skill 5.17.6)")

    sha, subject = canonical_commit(args.allow_unpushed)
    rev = skill_revision()
    print(f"release: canonical {sha[:12]} \"{subject}\" (skill {rev})")
    have = pin.read_text(encoding="utf-8").split()
    if have and have[0] == sha:
        print(f"release: {dest} already pins {sha[:12]}; nothing to land")
        return 0
    print(f"release: pin {have[0][:12] if have else '(empty)'} -> {sha[:12]}")
    pin.write_text(sha + "\n", encoding="utf-8")

    branch = f"sync/pipeline-{sha[:7]}"
    title = f"sync: pipeline {sha[:7]} (skill {rev}) — {subject}"
    body = (f"Pins {UPSTREAM_REPO} @ `{sha}` (skill {rev})\n\n"
            f"> {subject}\n\n"
            "Generated by `tools/release.py`; the diff is the one line of "
            "`skills/package-sciaccel-task/PIPELINE_REVISION`. CI checks the pipeline out at this commit.\n")
    if not args.pr:
        print("\nrelease: to land it:")
        print(f"  git -C {dest} checkout -b {branch}")
        print(f"  git -C {dest} add {PIN_REL}")
        print(f"  git -C {dest} commit -m {title!r}")
        print(f"  git -C {dest} push -u origin {branch}")
        print(f"  gh pr create --repo <benchmark> --head {branch} --title {title!r} --body '<see release.py>'")
        return 0

    current = git(dest, "rev-parse", "--abbrev-ref", "HEAD")
    if current != "main":
        raise SystemExit(f"release: the benchmark checkout is on {current!r}; --pr branches from main only")
    git(dest, "checkout", "-q", "-b", branch)
    git(dest, "add", "--", str(PIN_REL))
    git(dest, "commit", "-q", "-m", title)
    git(dest, "push", "-q", "-u", "origin", branch)
    proc = subprocess.run(["gh", "pr", "create", "--head", branch, "--title", title, "--body", body],
                          cwd=str(dest), capture_output=True, text=True)
    if proc.returncode != 0:
        print(proc.stderr.strip())
        raise SystemExit("release: branch pushed but `gh pr create` failed; open the PR by hand")
    print(f"release: opened {proc.stdout.strip()}")
    print("release: wait for the benchmark CI, then merge that PR. The benchmark checkout is left on the sync branch.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
